### ISSUE TITLE
Read/Write configuration (both global and per-program)

### ISSUE THREAD

**Issue by Skryvvara** [Skryvvara/FocusFrame#1]
## What is the desired functionality?

The offset position on both the x and y axes should be configurable as well as the desired window width and height (+ additional options in the future)

## What is the current behavior?

Values are hardcoded and can only be changed in the code

## What would be an ideal solution?

I'm thinking about keeping it relatively simple. I would like to have a GUI option in the end but ultimately it should probably be something like a toml or ini file. That could look like this

```toml
[Global]
offsetX=0
offsetY=0
windowWidth=2560
windowHeight=1440

[Baldurs Gate 3]
offsetX=0
offsetY=0
windowWidth=1920
windowHeight=1080
```
